export const GET_ALL_BLOG_REQUEST = 'GET_ALL_BLOG_REQUEST'
export const GET_ALL_BLOG_SUCCESS = 'GET_ALL_BLOG_SUCCESS'
export const GET_ALL_BLOG_FAIL = 'GET_ALL_BLOG_FAIL'

export const GET_BLOG_DETAILS_REQUEST = 'GET_BLOG_DETAILS_REQUEST'
export const GET_BLOG_DETAILS_SUCCESS = 'GET_BLOG_DETAILS_SUCCESS'
export const GET_BLOG_DETAILS_FAIL = 'GET_BLOG_DETAILS_FAIL'

