export const GET_PROJECT_COMMENTS_REQUEST = 'GET_PROJECT_COMMENTS_REQUEST'
export const GET_PROJECT_COMMENTS_SUCCESS = 'GET_PROJECT_COMMENTS_SUCCESS'
export const GET_PROJECT_COMMENTS_FAIL = 'GET_PROJECT_COMMENTS_FAIL'

export const CREATE_PROJECT_COMMENT_REQUEST = 'CREATE_PROJECT_COMMENT_REQUEST'
export const CREATE_PROJECT_COMMENT_SUCCESS = 'CREATE_PROJECT_COMMENT_SUCCESS'
export const CREATE_PROJECT_COMMENT_FAIL = 'CREATE_PROJECT_COMMENT_FAIL'
export const CREATE_PROJECT_COMMENT_RESET = 'CREATE_PROJECT_COMMENT_RESET'

export const GET_PROJECT_COMMENT_REPLIES_REQUEST = 'GET_PROJECT_COMMENT_REPLIES_REQUEST'
export const GET_PROJECT_COMMENT_REPLIES_SUCCESS = 'GET_PROJECT_COMMENT_REPLIES_SUCCESS'
export const GET_PROJECT_COMMENT_REPLIES_FAIL = 'GET_PROJECT_COMMENT_REPLIES_FAIL'

export const DELETE_PROJECT_COMMENT_REQUEST = 'DELETE_PROJECT_COMMENT_REQUEST'
export const DELETE_PROJECT_COMMENT_SUCCESS = 'DELETE_PROJECT_COMMENT_SUCCESS'
export const DELETE_PROJECT_COMMENT_FAIL = 'DELETE_PROJECT_COMMENT_FAIL'
export const DELETE_PROJECT_COMMENT_RESET = 'DELETE_PROJECT_COMMENT_RESET'

export const UPDATE_PROJECT_COMMENT_REQUEST = 'UPDATE_PROJECT_COMMENT_REQUEST'
export const UPDATE_PROJECT_COMMENT_SUCCESS = 'UPDATE_PROJECT_COMMENT_SUCCESS'
export const UPDATE_PROJECT_COMMENT_FAIL = 'UPDATE_PROJECT_COMMENT_FAIL'
export const UPDATE_PROJECT_COMMENT_RESET = 'UPDATE_PROJECT_COMMENT_RESET'