export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST'
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS'
export const GET_CITIES_FAIL = 'GET_CITIES_FAIL'


export const GET_MY_GIVE_JOB_FORMS_REQUEST = 'GET_MY_GIVE_JOB_FORMS_REQUEST'
export const GET_MY_GIVE_JOB_FORMS_SUCCESS = 'GET_MY_GIVE_JOB_FORMS_SUCCESS'
export const GET_MY_GIVE_JOB_FORMS_FAIL = 'GET_MY_GIVE_JOB_FORMS_FAIL'


export const SEND_FORM_REQUEST = 'SEND_FORM_REQUEST'
export const SEND_FORM_SUCCESS = 'SEND_FORM_SUCCESS'
export const SEND_FORM_FAIL = 'SEND_FORM_FAIL'
export const SEND_FORM_RESET = 'SEND_FORM_RESET'

export const GET_MY_TEAM_FORMS_REQUEST = 'GET_MY_TEAM_FORMS_REQUEST'
export const GET_MY_TEAM_FORMS_SUCCESS= 'GET_MY_TEAM_FORMS_SUCCESS'
export const GET_MY_TEAM_FORMS_FAIL = 'GET_MY_TEAM_FORMS_FAIL'

export const UPDATE_GIVE_JOB_FORM_REQUEST = 'UPDATE_GIVE_JOB_FORM_REQUEST'
export const UPDATE_GIVE_JOB_FORM_SUCCESS = 'UPDATE_GIVE_JOB_FORM_SUCCESS'
export const UPDATE_GIVE_JOB_FORM_FAIL = 'UPDATE_GIVE_JOB_FORM_FAIL'
export const UPDATE_GIVE_JOB_FORM_RESET = 'UPDATE_GIVE_JOB_FORM_RESET'

export const DELETE_GIVE_JOB_FORM_REQUEST = 'DELETE_GIVE_JOB_FORM_REQUEST'
export const DELETE_GIVE_JOB_FORM_SUCCESS = 'DELETE_GIVE_JOB_FORM_SUCCESS'
export const DELETE_GIVE_JOB_FORM_FAIL = 'DELETE_GIVE_JOB_FORM_FAIL'
export const DELETE_GIVE_JOB_FORM_RESET = 'DELETE_GIVE_JOB_FORM_RESET'

export const UPDATE_TEAM_FORM_REQUEST = 'UPDATE_TEAM_FORM_REQUEST'
export const UPDATE_TEAM_FORM_SUCCESS = 'UPDATE_TEAM_FORM_SUCCESS'
export const UPDATE_TEAM_FORM_FAIL = 'UPDATE_TEAM_FORM_FAIL'
export const UPDATE_TEAM_FORM_RESET = 'UPDATE_TEAM_FORM_RESET'

export const DELETE_TEAM_FORM_REQUEST = 'DELETE_TEAM_FORM_REQUEST'
export const DELETE_TEAM_FORM_SUCCESS = 'DELETE_TEAM_FORM_SUCCESS'
export const DELETE_TEAM_FORM_FAIL = 'DELETE_TEAM_FORM_FAIL'
export const DELETE_TEAM_FORM_RESET = 'DELETE_TEAM_FORM_RESET'

export const UPDATE_PROJECT_IDEA_FORM_REQUEST = 'UPDATE_PROJECT_IDEA_FORM_REQUEST'
export const UPDATE_PROJECT_IDEA_FORM_SUCCESS = 'UPDATE_PROJECT_IDEA_FORM_SUCCESS'
export const UPDATE_PROJECT_IDEA_FORM_FAIL = 'UPDATE_PROJECT_IDEA_FORM_FAIL'
export const UPDATE_PROJECT_IDEA_FORM_RESET = 'UPDATE_PROJECT_IDEA_FORM_RESET'

export const DELETE_PROJECT_IDEA_FORM_REQUEST = 'DELETE_PROJECT_IDEA_FORM_REQUEST'
export const DELETE_PROJECT_IDEA_FORM_SUCCESS = 'DELETE_PROJECT_IDEA_FORM_SUCCESS'
export const DELETE_PROJECT_IDEA_FORM_FAIL = 'DELETE_PROJECT_IDEA_FORM_FAIL'
export const DELETE_PROJECT_IDEA_FORM_RESET = 'DELETE_PROJECT_IDEA_FORM_RESET'

export const GET_MY_PROJECT_IDEA_FORMS_REQUEST = 'GET_MY_PROJECT_IDEA_FORMS_REQUEST'
export const GET_MY_PROJECT_IDEA_FORMS_SUCCESS = 'GET_MY_PROJECT_IDEA_FORMS_SUCCESS'
export const GET_MY_PROJECT_IDEA_FORMS_FAIL = 'GET_MY_PROJECT_IDEA_FORMS_FAIL'