export const GET_CITIES_REQUEST = 'GET_CITIES_REQUEST'
export const GET_CITIES_SUCCESS = 'GET_CITIES_SUCCESS'
export const GET_CITIES_FAIL = 'GET_CITIES_FAIL'

export const SEND_GIVE_JOB_FORM_REQUEST = 'SEND_GIVE_JOB_FORM_REQUEST'
export const SEND_GIVE_JOB_FORM_SUCCESS = 'SEND_GIVE_JOB_FORM_SUCCESS'
export const SEND_GIVE_JOB_FORM_FAIL = 'SEND_GIVE_JOB_FORM_FAIL'
export const SEND_GIVE_JOB_FORM_RESET = 'SEND_GIVE_JOB_FORM_RESET'

export const GET_MY_GIVE_JOB_FORMS_REQUEST = 'GET_MY_GIVE_JOB_FORMS_REQUEST'
export const GET_MY_GIVE_JOB_FORMS_SUCCESS = 'GET_MY_GIVE_JOB_FORMS_SUCCESS'
export const GET_MY_GIVE_JOB_FORMS_FAIL = 'GET_MY_GIVE_JOB_FORMS_FAIL'

export const UPDATE_MY_GIVE_JOB_FORMS_REQUEST = 'UPDATE_MY_GIVE_JOB_FORMS_REQUEST'
export const UPDATE_MY_GIVE_JOB_FORMS_SUCCESS = 'UPDATE_MY_GIVE_JOB_FORMS_SUCCESS'
export const UPDATE_MY_GIVE_JOB_FORMS_FAIL = 'UPDATE_MY_GIVE_JOB_FORMS_FAIL'
export const UPDATE_MY_GIVE_JOB_FORMS_RESET = 'UPDATE_MY_GIVE_JOB_FORMS_RESET'

export const DELETE_MY_GIVE_JOB_FORMS_REQUEST = 'DELETE_MY_GIVE_JOB_FORMS_REQUEST'
export const DELETE_MY_GIVE_JOB_FORMS_SUCCESS = 'DELETE_MY_GIVE_JOB_FORMS_SUCCESS'
export const DELETE_MY_GIVE_JOB_FORMS_FAIL = 'DELETE_MY_GIVE_JOB_FORMS_FAIL'
export const DELETE_MY_GIVE_JOB_FORMS_RESET = 'DELETE_MY_GIVE_JOB_FORMS_RESET'