export const GET_ALL_PROJECT_REQUEST = 'GET_ALL_PROJECT_REQUEST'
export const GET_ALL_PROJECT_SUCCESS = 'GET_ALL_PROJECT_SUCCESS'
export const GET_ALL_PROJECT_FAIL = 'GET_ALL_PROJECT_FAIL'


export const GET_PROJECT_DETAILS_REQUEST = 'GET_PROJECT_DETAILS_REQUEST'
export const GET_PROJECT_DETAILS_SUCCESS = 'GET_PROJECT_DETAILS_SUCCESS'
export const GET_PROJECT_DETAILS_FAIL = 'GET_PROJECT_DETAILS_FAIL'

