
export const GET_USER_COMMENTS_REQUEST = 'GET_USER_COMMENTS_REQUEST'
export const GET_USER_COMMENTS_SUCCESS = 'GET_USER_COMMENTS_SUCCESS'
export const GET_USER_COMMENTS_FAIL = 'GET_USER_COMMENTS_FAIL'