
export const GET_USER_COMMENTS_REQUEST = 'GET_USER_COMMENTS_REQUEST'
export const GET_USER_COMMENTS_SUCCESS = 'GET_USER_COMMENTS_SUCCESS'
export const GET_USER_COMMENTS_FAIL = 'GET_USER_COMMENTS_FAIL'



export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAIL = 'GET_PROFILE_FAIL'

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'
export const UPDATE_PROFILE_RESET = 'UPDATE_PROFILE_RESET'